### ISSUE TITLE
WebGui Crashing DSL-AC68U

### ISSUE THREAD

**Issue by frizby66** [gnuton/asuswrt-merlin.ng#104]
Anyone else experiencing the webgui crashing after a few hours?

Did a NVRAM clearcut (WPS button press on power up) and factory reset, then latest firmware update, reset again and JFS format...worked for a few hours and then crashes. Still able to access web and other devices, just not the router. Trying to remote access at the moment via SSH but struggling a little. Dive is remote, not local.

**Comment by gnuton** [comment]
Hi,
This is most probably due to something wrong on your setup.
Pleae ask in the forum for more help then open a ticket for developers when it's clear what has to be fixed, if any.

BTW please when you open a ticket remember to:
1. Write all the steps to reproduce it
2. Send us clea proof of what happaned: For instance if you couldshow me the logs which say httpd has crashed or you can ssh into the router and show me that httpd PID has changed without you doying anything.

Thanks a lot for.
As for now this bug is invalid since there are not enough information about this issue.
Feel free to re-open if you have more info for making this reproducible to developers.
