### ISSUE TITLE
DSL-N16 Support

### ISSUE THREAD

**Issue by Unconsiusplus** [gnuton/asuswrt-merlin.ng#188]
I looked a lot of alternatives for asuswrt most of the DSL series are not compatible all of them and only your version is compatible. 
DSL-N16 is older but very common modem in East Europe, Middle East and west Asia because of its reasonable price.
Can you add DSL-N16 support or would you provide me how to build/ fork my modem. I have DSL N16 source code, but I think just upgrading kernel and statistic functions with basic understanding of C, copying files etc., modding them with very low stuff. But if adding support is easier than this, just one working version of modded merlin version enough for all. This modem has high DSL disconnect rate and Users of this modem mostly needs DSL SNR and SNR related statistics graphs and DSL stability improvements (DSL driver update etc.)

**Comment by gnuton** [comment]
Hi DSL-N16 is a mediatek based router and he canot support merlin which is for broadcom routers.
I have some mediatek code here https://github.com/gnuton/asus-mediatek-fw
but the DSL-N16 is missing so you have to grab it from Asus support website.

As for building you can use this docker image https://github.com/gnuton/asus-mediatek-toolchains-docker
You can hardly add so much stuff there becasue the linux kernel is old and cannot be upgraded since that SoC is not supported  by newer kernels. Running a such old kernel and software is not safe since it can be full of vulnerabilities.
Moreover the router doesn't have enough CPU/mem power to run additional stuff.

I will close this task since this is not an enachement for Merlin
