### ISSUE TITLE
Alpha: Stability Adjustment 388

### ISSUE THREAD

**Issue by Hello-olleH** [gnuton/asuswrt-merlin.ng#296]
**Router Model Affected**
Models: DSL-AX82U

**Firmware Version Affected**
 388.1_0-gnuton0_beta1

**Is this bug present in upstream Merlin releases too?**
No

**Describe the bug**
Every change in Stability Adjustment causes Link down 

**To Reproduce**
.../Advanced_ADSL_Content.asp
Change Stability Adjustment to any

**Expected behavior**

**Screenshots**
<img width="870" alt="Screenshot 2022-12-02 at 18 23 02" src="https://user-images.githubusercontent.com/45637723/205351746-62b7a5a6-13b4-433e-a0e8-87371bc0ad09.png">
<img width="872" alt="Screenshot 2022-12-02 at 18 09 00" src="https://user-images.githubusercontent.com/45637723/205351802-ffa14b5e-a0fb-4f6c-a3b5-4a2e0b40b7de.png">

**Comment by gnuton** [comment]
Thanks for reporting.
This happens because because there is a switch from the newer to an older driver under the hood and this mechanism seems tobe broken on 388 alphas and betas.
I am trying to understand what's breaking it..
In any case I am already tracking this issue here https://github.com/gnuton/asuswrt-merlin.ng/issues/290
so if you do not mind for avoding duplicates please follow the other issue, and I will close this one.
