### ISSUE TITLE
RT-AX82u v2 3004.388.4_0-knuton0_beta1 missing WiFi_Insight.asp file

### ISSUE THREAD

**Issue by TelecomDoctor** [gnuton/asuswrt-merlin.ng#476]
**Router Model Affected**
RT-AX82u v2 

**Firmware Version Affected**
3004.388.4_0-knuton0_beta1

**Is this bug present in upstream Merlin releases too?**
Not known

**Describe the bug**
Getting a "404 file not found for WiFi_Insight.asp

Possible missing 
**To Reproduce**
1. Go to 'Network Tools'
2. Click on 'WiFi Radar'
3. See 404 error

**Comment by Imastupidsalmon** [comment]
This issue is also occuring on the rt-ax5400. 3004.388.6_alpha1

**Comment by gnuton** [comment]
this should be fixed, do you confirm?

**Comment by Imastupidsalmon** [comment]
@gnuton I can confirm that in the RT-AX5400 it is indeed fixed in the latest build. Nice. 👍 Thank you!
Super cool!!
![Screenshot_20240213-142605_Chrome](https://github.com/gnuton/asuswrt-merlin.ng/assets/134196913/5b30be54-8b84-431b-9a22-df88f0a2c4ca)
![Screenshot_20240213_142742](https://github.com/gnuton/asuswrt-merlin.ng/assets/134196913/7e0d6273-efc2-43b5-9221-f7cf2fe7a668)

**Comment by gnuton** [comment]
Awesome thanks I will close this issue.
