### ISSUE TITLE
Dnsmasq version issue (CVE 2023-50868 and CVE 2023-50387)

### ISSUE THREAD

**Issue by Jacky10X** [gnuton/asuswrt-merlin.ng#548]
Model: TUF-AX3000 
Firmware version: TUF-AX3000_3004_388.6_0-gnuton1

Hello, Sorry to bother you.
Gnuton build is currently using the dnsmasq 2.89 version if I check it correctly. It seems this version does not resolve the CVE 2023-50868 and CVE 2023-50387 issues.

Asuswrt-Merlin updated the dnsmasq to 2.90 to resolve CVE 2023-50868 and CVE 2023-50387
[Asuswrt-Merlin 3004.388.6_2]

Do you have any plans to update the dnsmasq in the future?

**Comment by gnuton** [comment]
Usually these updates are covered from upstream. @RMerl

**Comment by gnuton** [comment]
Yes I will release soon

**Comment by Jacky10X** [comment]
@gnuton hello, that is good new but dnsmasq has 2.91 version which fix spurious "resource limit exceeded messages" issue.

**Comment by RMerl** [comment]
2.90 is still the latest version available as of today.  Simon hasn't released a new update yet following the post-2.90 fixes.

That fix was already [backported](https://github.com/RMerl/asuswrt-merlin.ng/commit/e9fea56583aebe465a4a57249bdfd3cdd9f2f5d1) to my repo (as well as other post-2.90 fixes available upstream), so that fix will also be included whenever @gnuton merges my code in.

**Comment by Jacky10X** [comment]
@RMerl thank you for answering and asuswrt-merlin. So fixes will be included in next update. That is also great news.

**Comment by gnuton** [comment]
@Jacky10X the code has been merged today and I have released the _2 alpha.

**Comment by gnuton** [comment]
Since the alpha are out.. I will close this.. 
this will naturally be part of the next stable when out. so no actions nor anything to track.. just wait update the the latest pre and stable releases.
